### ISSUE TITLE
Node related events are broken

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#681]
Fixed in https://github.com/kubernetes/kubernetes/pull/18462 on master.

**Comment by jdef** [comment]
context please.. :)

**Comment by sttts** [comment]
It's only a reminder for myself. We know the issue and have a fix. Will give context soon. All events for nodes are broken on master.

**Comment by sttts** [comment]
Here is the issue: https://github.com/kubernetes/kubernetes/issues/18460. 

This is not testable to easily because events do not survive forever. The missing events are only for existing nodes which might be created long ago.

I have delegated to @gmarek who did the causing patch. One of the two reference code blocks must go away.

**Comment by sttts** [comment]
It looks like this is not cherry picked onto the release branch. Hence, this is not an issue for v0.7.1. I will postpone to v0.7.2. Then we can check whether it's fixed (or still not cherry-picked).

**Comment by gmarek** [comment]
cc @mqliang @wojtek-t

**Comment by sttts** [comment]
@gmarek can you confirm the missing events also on your test cluster? Have found this on Mesos of course.

**Comment by sttts** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/18462

**Comment by jdef** [comment]
Node validation is still not picked into the release-1.1 branch, fix not needed in v0.7.2
